<!-- BEGIN -->
<form action="/users" method="get">
    <input type="search" required name="search">
    <input type="submit" value="Search">
</form>

<table>
    <tr>
        <th>id</th>
        <th>firstName</a></th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?= $user['id'] ?>
            </td>
            <td>
                <a href="/users/<?= $user['id'] ?>"><?= $user['firstName'] ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<!-- END -->