<a href="/users">Пользователи</a>

<!-- BEGIN (write your solution here) -->
<table>
    <tr>
        <th>id</th>
        <th>firstName</th>
        <th>lastName</th>
        <th>email</th>
    </tr>
    <tr>
        <td>
            <?= $user['id'] ?>
        </td>
        <td>
            <?= $user['firstName'] ?>
        </td>
        <td>
            <?= $user['lastName'] ?>
        </td>
        <td>
            <?= $user['email'] ?>
        </td>
    </tr>
</table>
<!-- END -->